=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
    targetNamespace="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator"
    elementFormDefault="qualified"
    xmlns="urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <xs:include schemaLocation="Plazacraft.HOMM3.DamageSymulator.Definition.xsd" />
 
  <xs:element name="Fight" type="Fight" />
  
  <xs:complexType name="Fight" > 
    <xs:all>
      <xs:element name="Attacker" type="Hero" minOccurs="1" />
      <xs:element name="Defender" type="Hero" minOccurs="1" />
    </xs:all>
    <xs:attribute name="Terrain" type="Terrain" use="required" />
  </xs:complexType>

  <xs:complexType name="Hero">
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">      
          <xs:element name="Creature" minOccurs="0" maxOccurs="unbounded" type="CreatureRef" />
          <xs:element name="SecondarySkill" minOccurs="0" maxOccurs="unbounded" type="Reference" />
          <xs:element name="HeroAbility" minOccurs="0" maxOccurs="unbounded" type="Reference" />
        </xs:choice> 
    </xs:sequence> 
    <xs:attribute name="Attack" type="xs:int" use="required" />
    <xs:attribute name="Defense" type="xs:int" use="required" />
    <xs:attribute name="Level" type="xs:int" use="required" />
  </xs:complexType>

  <xs:complexType name="CreatureRef">
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">      
          <xs:element name="Spell" minOccurs="0" maxOccurs="unbounded" type="Reference" />
          <xs:element name="Param" minOccurs="0" maxOccurs="unbounded" type="Param" />
        </xs:choice>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Count" type="xs:int" use="required" />
    <xs:attribute name="AttackType" type="AttackType" use="required" />
    <xs:attribute name="Luck" type="xs:boolean" use="optional" default="false" />
    <xs:attribute name="RangePenalty" type="Penalty" use="optional" default="None" />
    <xs:attribute name="ObstaclePenalty" type="Penalty" use="optional" default="None" />
  </xs:complexType>
   
  <xs:complexType name="Param">
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Value" type="xs:int" use="required" />
  </xs:complexType>
    
  <xs:simpleType name="Penalty">
    <xs:list>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="None"/>
          <xs:enumeration value="value50"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:list>
  </xs:simpleType>
  


</xs:schema>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/3-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Griffin' Count='17' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wood Elf' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Stone Golem' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Hell Hound' Count='13' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wight' Count='14' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Beholder' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Orc' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Serpent Fly' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Water Elemental' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Pirate' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Mummy' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nomad' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Griffin' Count='17' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wood Elf' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Stone Golem' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Hell Hound' Count='13' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wight' Count='14' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Beholder' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Orc' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Serpent Fly' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Water Elemental' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Pirate' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Mummy' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nomad' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/1-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Pikeman' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Centaur' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gremlin' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Imp' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Skeleton' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Troglodyte' Count='35' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Goblin' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gnoll' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Pixie' Count='50' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nymph' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Peasant' Count='25' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Halfling' Count='15' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Pikeman' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Centaur' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gremlin' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Imp' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Skeleton' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Troglodyte' Count='35' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Goblin' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gnoll' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Pixie' Count='50' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nymph' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Peasant' Count='25' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Halfling' Count='15' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/1u-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Halaberdier' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Centaur captain' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Master Gremlin' Count='32' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Familiar' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Skeleton Warrior' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Infernal Troglodyte' Count='35' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Hobgoblin' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gnoll Marauder' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Sprite' Count='50' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Oceanid' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Peasant' Count='25' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Halfling' Count='15' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Halaberdier' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Centaur captain' Count='28' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Master Gremlin' Count='32' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Familiar' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Skeleton Warrior' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Infernal Troglodyte' Count='35' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Hobgoblin' Count='38' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gnoll Marauder' Count='30' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Sprite' Count='50' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Oceanid' Count='32' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Peasant' Count='25' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Halfling' Count='15' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/2-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Archer' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Dwarf' Count='20' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Stone Gargoyle' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gog' Count='16' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Walking Dead' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Harpy' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wolf Rider' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Lizardman' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Air Elemental' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Crew Mate' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Boar' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Rogue' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Leprechaun' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Archer' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Dwarf' Count='20' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Stone Gargoyle' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Gog' Count='16' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Walking Dead' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Harpy' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wolf Rider' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Lizardman' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Air Elemental' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Crew Mate' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Boar' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Rogue' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Leprechaun' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/3u-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Royal Griffin' Count='17' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Grand Elf' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Iron Golem' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Cerberus' Count='13' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wraith' Count='14' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Evil Eye' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Orc Chieftain' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Dragon Fly' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Ice Elemental' Count='12' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Corsair' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Sea Dog' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Mummy' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nomad' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Royal Griffin' Count='17' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Grand Elf' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Iron Golem' Count='12' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Cerberus' Count='13' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wraith' Count='14' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Evil Eye' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Orc Chieftain' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Dragon Fly' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Ice Elemental' Count='12' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Corsair' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Sea Dog' Count='14' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Mummy' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Nomad' Count='7' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>

=== plazacraft/Plazacraft.App.HOMM3/DamageSymulator/Examples/2u-Level Fight.xml
<Fight Terrain='Sand' xsi:schemaLocation='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator http://homm3.plazacraft.com/damagesymulator/schemas/Plazacraft.HOMM3.DamageSymulator.Fight.xsd' xmlns='urn:x-plazacraft.org:plazacraft.homm3-1.0-damagesymulator' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Attacker Attack='0' Defense='0' Level='0'>
        <Creature Name='Marksman' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Battle Dwarf' Count='20' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Obsidian Gargoyle' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Magog' Count='16' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Zombie' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Harpy Hag' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wolf Raider' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Lizard Warrior' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Storm Elemental' Count='12' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Seaman' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Boar' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Rogue' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Leprechaun' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Attacker>
    <Defender Attack='0' Defense='0' Level='0'>
        <Creature Name='Marksman' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Battle Dwarf' Count='20' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Obsidian Gargoyle' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Magog' Count='16' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Zombie' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Harpy Hag' Count='16' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Wolf Raider' Count='18' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Lizard Warrior' Count='18' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Storm Elemental' Count='12' AttackType='Ranged' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Seaman' Count='22' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Boar' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Rogue' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
        <Creature Name='Leprechaun' Count='8' AttackType='Melee' Luck='false' RangePenalty='None' ObstaclePenalty='None'/>
    </Defender>
</Fight>
